name: lp-build-snap
version: git
summary: Utility to trigger Snap package builds in Launchpad
description: |
  A command-line tool that lets you trigger Snap package builds in Launchpad
  manually or from CI
grade: stable
confinement: strict
base: core24
platforms:
  amd64: 
  arm64: 
  armhf:

apps:
  lp-build-snap:
    command: usr/bin/lp-build-snap
    plugs: [desktop, network]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    
parts:
  lp-build-snap:
    plugin: dump
    source: .
    organize:
      lp-build-snap: usr/bin/lp-build-snap

  python-deps:
    plugin: python
    source: .
    python-packages:
      - launchpadlib==2.0.0
      - keyring==25.2.1
    organize:
      lib/python3.12/site-packages: usr/lib/python3/dist-packages
      bin: usr/bin
    prime:
      - usr/bin/distro
      - usr/bin/keyring
      - usr/lib
